name: Create Release for Jump to Emby

on:
  push:
    tags:
      - 'jump_to_emby_v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Extract version and changelog
        id: extract_info
        run: |
          # 提取版本号
          VERSION=${GITHUB_REF#refs/tags/jump_to_emby_v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          # 提取标签消息作为更新日志
          TAG_MESSAGE=$(git tag -l --format='%(contents)' jump_to_emby_v$VERSION)
          TAG_MESSAGE="${TAG_MESSAGE//$'\n'/'%0A'}"
          echo "CHANGELOG=$TAG_MESSAGE" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Jump to Emby v${{ steps.extract_info.outputs.VERSION }}
          body: |
            Jump to Emby v${{ steps.extract_info.outputs.VERSION }} 发布了！
            
            ## 更新内容
            ${{ steps.extract_info.outputs.CHANGELOG }}
          files: |
            scripts/Jump_to_Emby/Jump_to_Emby.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}