name: Update Jump to Emby to Greasy Fork

on:
  push:
    tags:
      - 'jump_to_emby_v*'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (如 1.2.3)'
        required: true
      changelog:
        description: '自定义更新说明 (可选)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 获取发布信息
        id: get-info
        run: |
          # 公共函数：获取提交信息
          get_commit_message() {
            local tag_name="$1"
            local repo="${{ github.repository }}"
            
            # 第一步：获取标签引用
            ref_info=$(curl -sS -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$repo/git/ref/tags/$tag_name")
            
            # 解析对象类型和SHA
            obj_type=$(echo "$ref_info" | jq -r '.object.type')
            obj_sha=$(echo "$ref_info" | jq -r '.object.sha')

            # 循环解析嵌套标签对象
            while [[ "$obj_type" == "tag" ]]; do
              tag_info=$(curl -sS -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/$repo/git/tags/$obj_sha")
              obj_type=$(echo "$tag_info" | jq -r '.object.type')
              obj_sha=$(echo "$tag_info" | jq -r '.object.sha')
            done

            # 获取最终提交信息
            commit_info=$(curl -sS -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$repo/git/commits/$obj_sha")
            echo "$commit_info" | jq -r '.message'
          }

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # 手动触发模式
            version="${{ github.event.inputs.version }}"
            tag_name="jump_to_emby_v$version"
            
            # 优先使用手动输入的更新说明
            if [[ -n "${{ github.event.inputs.changelog }}" ]]; then
              release_notes="${{ github.event.inputs.changelog }}"
            else
              release_notes=$(get_commit_message "$tag_name")
            fi
          else
            # 自动触发模式
            version="${GITHUB_REF#refs/tags/jump_to_emby_v}"
            tag_name="jump_to_emby_v$version"
            release_notes=$(get_commit_message "$tag_name")
          fi

          # 设置输出参数
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$release_notes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && format('jump_to_emby_v{0}', steps.get-info.outputs.version) || github.ref }}
          name: 'Jump to Emby v${{ steps.get-info.outputs.version }}'
          body: |-
            ## 更新日志
            ${{ steps.get-info.outputs.release_notes }}

            > 提交哈希：${{ github.sha }}
          files: |
            scripts/Jump_to_Emby/Jump_to_Emby.user.js
            scripts/Jump_to_Emby/README.md